### ISSUE TITLE
[Website]   [zetacoin] Could not dumpprivkey for zetacoin

### ISSUE THREAD

**Issue by LoRdMiCk** [zone117x/node-open-mining-portal#448]
anybody can help me I got this message when I start 
im using nomp as a p2p pool
the daemon is running and is synced..

2016-02-20 02:12:43 [Master]    [PoolSpawner] Spawned 1 pool(s) on 1 thread(s)
2016-02-20 02:12:43 [Website]   [Server] Website started on 0.0.0.0:7080
2016-02-20 02:12:43 [Website]   [.coinname.] Could not dumpprivkey for coinname {"type":"offline","message":"connect ECONNREFUSED"}

**Comment by barrystyle** [comment]
Not a bug/issue.
 
NOMP can't connect to your daemon because it is getting actively refused on the address/port you've setup.

Run zetacoin using the following (assuming it is on the same host as NOMP):
./zetacoind -server -daemon -rpcuser=test -rpcpass=test1234 -rpcbind=127.0.0.1 -rpcallowip=127.0.0.1 -maxconnections=12

In NOMP, configure the daemon with username and password, then address as '127.0.0.1' and rpcport as '17335'.

**Comment by LoRdMiCk** [comment]
did it already and it doesnt work.. pool work OK but stil get this error when I start it.. I have 2 different coin running right now and everything is working..

**Comment by LoRdMiCk** [comment]
found it.. this was set false..
 "paymentProcessing": {
        "enabled": true,
