### ISSUE TITLE
Total Blocks are not updating

### ISSUE THREAD

**Issue by AlexanderKozhevin** [zone117x/node-open-mining-portal#463]
We got 6.50 GH, but the Total Blocks are not updating. It's 0. 
How can we track an issue? Within the console I don't see explicit errors.
What is could be?

![screen shot 2016-09-03 at 11 43 06](https://cloud.githubusercontent.com/assets/4464561/18223823/dc00b796-71cb-11e6-9a22-a677781c274b.png)

**Comment by leshacat** [comment]
**blocknotify** I just solved this issue myself :)

**Open walletd.conf and add in line:**
> port=17000
> blocknotify=node /PATH/TO/NOMP/scripts/cli.js blocknotify mogwaicoin %s
Change port number, or just note what it is set to
Change /PATH/TO/NOMP to point to your NOMP installation (chmod install dir to 755 if still not work)
Change "mogwaicoin" to the name of the coin inside pool_conf/coinname.json

**Edit /PATH/TO/NOMP/scripts/cli.js:**
> var defaultPort = 17000;
> var defaultHost = '127.0.0.1';
Change port number to match port number from above

Now restart both walletd and NOMP

Your next blocks mined should show up as "PENDING" - I have yet to get it to move them to "CONFIRMED" but I suspect it is due to a payment system error.

Let me know if that works :D

**Comment by AlexanderKozhevin** [comment]
@leshacat If it works I can close this issues. 
But I haven't touched this code for 2 years, so have no idea what's going on now.
